<a href="https://colab.research.google.com/github/Jair-art/Nube/blob/main/Clase0107.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# Pivotear, es decir, multiplicar el primer renglon por su inversa

A = [[2,1,4,1],[3,4,-1,-1],[1,-4,1,5],[2,2,1,3]]
A = np.array(A)

In [ ]:
x = np.zeros(4)
x

array([0., 0., 0., 0.])

In [ ]:
a00 =

In [ ]:
A = [[11,2,3],[-4,5,8],[1,0,1]]
A = np.array(A)

x = [2,4,3]

In [ ]:
A[0] = A[0]*(1/A[0,0])
A[0]

array([1, 0, 0])

In [ ]:
A[1] = A[1]*(1/A[1,1])
A[1]

array([0, 1, 1])

In [ ]:
A

array([[11,  2,  3],
       [-4,  5,  8],
       [ 1,  0,  1]])

In [ ]:
for i in range(3):
  print(A[i,:])

[1 0 0]
[0 1 1]
[1 0 1]


In [ ]:
A[0,:]

array([1, 0, 0])

In [ ]:
A = [[11,2,3],[-4,5,8],[1,0,1]]
A = np.array(A, float)
A

array([[11.,  2.,  3.],
       [-4.,  5.,  8.],
       [ 1.,  0.,  1.]])

In [ ]:
A[0] = A[0]/A[0,0]
A

array([[ 1.        ,  0.18181818,  0.27272727],
       [-4.        ,  5.        ,  8.        ],
       [ 1.        ,  0.        ,  1.        ]])

In [ ]:
A[0]/A[0,0]

array([1.        , 0.18181818, 0.27272727])

In [ ]:
A[0,:]/A[0,0]

array([1.        , 0.18181818, 0.27272727])

In [ ]:
for m in range(len(A)):
  A[m,:] /= A[m,m]

In [ ]:
A

array([[ 1.        ,  0.18181818,  0.27272727],
       [-0.8       ,  1.        ,  1.6       ],
       [ 1.        ,  0.        ,  1.        ]])

In [39]:
A = [[11,2,3],[-4,5,8],[1,0,1]]
A = np.array(A, float)
A

array([[11.,  2.,  3.],
       [-4.,  5.,  8.],
       [ 1.,  0.,  1.]])

In [36]:
for m in range(len(A)):
  A[m,:] /= A[m,m]
A

array([[ 1.        ,  0.18181818,  0.27272727],
       [-0.8       ,  1.        ,  1.6       ],
       [ 1.        ,  0.        ,  1.        ]])

In [44]:
for m in range(len(A)):
  A[m,:] /= A[m,m]
  for i in range(len(A)):
    for j in range(i+1,len(A)):
        A[j] =  A[j] - A[j,i]*A[i]

In [45]:
A

array([[1.        , 0.18181818, 0.27272727],
       [0.        , 1.        , 1.58730159],
       [0.        , 0.        , 1.        ]])

In [22]:
A[1] =  A[1] - A[1,0]*A[0]


In [23]:
A

array([[1.        , 0.18181818, 0.27272727],
       [0.        , 1.14545455, 1.81818182],
       [1.        , 0.        , 1.        ]])

In [26]:
A[2] =  A[2] - A[2,0]*A[0]

In [27]:
A

array([[ 1.        ,  0.18181818,  0.27272727],
       [ 0.        ,  1.14545455,  1.81818182],
       [ 0.        , -0.18181818,  0.72727273]])

In [32]:
len(A)

3