<h1 align="center">Física Computacional.</h1>
<h1 align="center">Semestre 2015-2</h1>

<h2>Sergio A. Alcalá Corona </h2> 

---
### Rodrigo Vega Vilchis
### Daniel Rojo Mata
---

<h1 align="center">Programación para la física computacional</h1> 

## Práctica 1.  Programación básica


### Programación básica para la física

---

### **EJERCICIOS**:

$\;$

#### **1. Altitud de un satélite**: se va a lanzar un satélite en una órbita circular alrededor de la Tierra de modo que orbite el planeta una vez cada $T$ segundos.

#### **(a)** Demuestre que la altitud $h$ sobre la superficie de la Tierra que debe tener el satélite es:

<h3 align="center">$h = \biggl( {GMT^2\over4\pi^2} \biggr)^{1/3} - R$,</h3> 

donde $G = 6,67 × 10^{−11} m^3 kg^{−1}s^{−2}$ es la constante gravitatoria de Newton, $M = 5,97 ×
1024 kg$ es la masa de la Tierra, y $R = 6371 km$ es su radio.




#### **(b)** Escribe un programa que le pida al usuario que ingrese el valor deseado de $T$ y luego calcule e imprima la altura correcta en metros.


#### **(c)** Utiliza tu programa para calcular las altitudes de los satélites que orbitan la Tierra una vez al día (la llamada *órbita "geosincrónica"*), una vez cada **90 minutos** y una vez cada **45 minutos**. 
#### ¿Qué concluyes del último de estos cálculos?

#### **2. Relatividad especial:** Una nave espacial viaja desde la Tierra en línea recta a una velocidad relativista $v$ a otro planeta a $x$ años luz de distancia. 

#### Escribe un programa que le pida al usuario el valor de $x$ y la velocidad $v$ como una fracción de la velocidad de la luz $c$, y que imprima el tiempo en años que tarda la nave espacial en llegar a su destino

#### **(a)** en el marco de reposo de un observador en la Tierra y

In [7]:
v = float(input("Ingrese la velocidad de la nave:"))
x = float(input("Ingrese la distancia al planeta:"))

Ingrese la velocidad de la nave: 0.3
Ingrese la distancia al planeta: 19.6


In [5]:
input?

Signature: input(prompt='')
Docstring:
Forward raw_input to frontends

Raises
------
StdinNotImplementedError if active frontend doesn't support stdin.
File:      /usr/lib/python3.13/site-packages/ipykernel/kernelbase.py
Type:      method

#### **(b)** como lo percibiría un pasajero a bordo de la nave. 

#### Usa tu programa para calcular las respuestas para un planeta a 10 años luz de distancia con $v = 0.99c$

#### **3. Órbitas planetarias**: En el espacio, la órbita de un cuerpo alrededor de otro (como un planeta alrededor del Sol), no necesariamente es circular. En general, toma la forma de una elipse, con el cuerpo a veces más cerca y otras más lejos. Si tenemos la distancia $\ell_1$ de máxima aproximación de un planeta al Sol (su \textit{perihelio}), y su velocidad lineal $v_1$ en el perihelio, entonces cualquier otra propiedad de la órbita se puede calcular a partir de estas dos cantidades de la siguiente manera:

#### **(a)** La segunda ley de Kepler nos dice que la distancia $\ell_2$ y la velocidad $v_2$ del planeta en su punto más distante, o \textit{afelio}, satisfacen que $\ell_2 v_2 = \ell_1 v_1$.  Al mismo tiempo, la energía total, cinética más la gravitatoria, de un planeta con velocidad $v$ y distancia $r$ del Sol está dada por:

<h3 align="center">$E = \frac{1}{2} m v^2 - G {mM\over r}$,</h3>
       
#### donde $m$ es la masa del planeta, $M=1.9891\times10^{30}\,$kg es la masa del Sol y $G=6.6738\times10^{-11}\,\mathrm{m^3\,kg^{-1}\,s^{-2}}$ es la constante gravitatoria de Newton. Dado que la energía debe conservarse, demuestre que $v_2$ es la raíz más pequeña de la ecuación cuadrática:

<h3 align="center">$v_2^2 - {2GM\over v_1\ell_1} v_2 - \biggl[ v_1^2 - {2GM\over\ell_1} \biggr] = 0$.</h3>

#### Una vez que tenemos $v_2$ podemos calcular $\ell_2$  usando la relación $\ell_2 = \ell_1 v_1/v_2$.


#### **(b)**  Dados los valores de $v_1$, $\ell_1$, y $\ell_2$; otros parámetros de la órbita se obtienen mediante fórmulas simples que pueden derivarse de las leyes de Kepler y del hecho de que la órbita es una elipse:

<h4 align="center"><b>Semieje mayor</b>: $\; \; \; a = \frac{1}{2}(\ell_1+\ell_2),$</h3>

<h4 align="center"><b>Semieje menor</b>: $\; \; b = \sqrt{\ell_1\ell_2},$</h3>

<h4 align="center"><b>Período orbital</b>: $\; \; T = {2\pi ab\over\ell_1 v_1},$</h3>

<h4 align="center"><b>Excentricidad orbital</b>: $\; \; e = {\ell_2-\ell_1\over\ell_2+\ell_1},$</h3>

#### Escribe un programa que le pida al usuario que ingrese la distancia al Sol y la velocidad en el perihelio; para que calcule e imprima las cantidades $\ell_2$, $v_2$, $T$ y $e$.


In [11]:
from math import pi 

In [12]:
T = (2*pi*a*b)/(l_1*v_1)

NameError: name 'a' is not defined

#### **(c)** Prueba tu programa haciendo que calcule las propiedades de las órbitas de la Tierra (para las cuales $\ell_1=1.4710\times10^{11}\,$m y $v_1=3.0287\times10^4\,\mathrm{m\,s^{-1}}$)  y del cometa Halley ($\ell_1=8.7830\times10^{10}\,$m y $v_1=5.4529\times10^4\,\mathrm{m\,s^{-1}}$). Entre otras cosas, deberías encontrar que el período orbital de la Tierra es de un año y el del cometa Halley es de unos 76 años.

In [1]:
import numpy as np

In [2]:
A = [[11,2,3],[-4,5,8],[1,0,1]]
A = np.array(A, float)
A

array([[11.,  2.,  3.],
       [-4.,  5.,  8.],
       [ 1.,  0.,  1.]])

In [82]:
for m in range(len(A)):
  A[m,:] /= A[m,m]
  for i in range(len(A)):
    for j in range(i+1,len(A)):
        A[j] =  A[j] - A[j,i]*A[i]
     

In [83]:
A

array([[ 1.        ,  1.3076468 ,  0.30513697,  0.52503273],
       [ 0.        ,  1.        , -0.62387203,  0.26799087],
       [ 0.        ,  0.        ,  1.        , -0.71501045],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [45]:

A = np.random.rand(10,10)
b = np.random.rand(10)  

In [43]:
A

array([[0.04386626, 0.75098511, 0.61924307, 0.73736128, 0.68876039,
        0.90059046, 0.07760053, 0.36389017, 0.72179596, 0.07958632],
       [0.30375763, 0.96763284, 0.55551308, 0.3642416 , 0.02671541,
        0.58441092, 0.54143586, 0.28340405, 0.58622815, 0.55408678],
       [0.68626311, 0.74876254, 0.19648707, 0.93031212, 0.52512349,
        0.99764509, 0.52955588, 0.18128496, 0.51343123, 0.05529724],
       [0.51054422, 0.92422599, 0.06774397, 0.53250644, 0.0016478 ,
        0.89741179, 0.65781929, 0.15348903, 0.02392961, 0.81480461],
       [0.90331185, 0.31263545, 0.41233813, 0.45001623, 0.14540099,
        0.27223007, 0.86811738, 0.31397858, 0.17869398, 0.1041287 ]])

In [46]:
b

array([0.87049868, 0.1163215 , 0.0050905 , 0.52178274, 0.73671744,
       0.04566488, 0.44197039, 0.95188216, 0.24260389, 0.93122146])

In [53]:
for m in range(len(b)):
  b[m] /= A[m,m]
  for i in range(len(b)):
    for j in range(i+1,len(b)):
        b[j] =  b[j] - A[j,i]*b[i]

In [54]:
b

array([ 4.21898324e+01, -2.71811343e+02,  2.69761142e+03, -1.80533760e+04,
        1.75754903e+04,  8.23614998e+03,  1.78214762e+04, -1.87498853e+05,
        2.80706025e+05,  1.96807353e+06])

In [60]:
x = np.zeros(4)

In [61]:
x[3] = b[3]

In [63]:
x[2] = - A[1,2]*b[1 ] + b[1]

In [64]:
x[1] = -A[2,1]*

array([     0.        ,      0.        ,   -355.53132322, -18053.3759875 ])

Codigo Profe

In [93]:
A = np.random.rand(4,4)
b = np.random.rand(4)  

In [94]:
A

array([[0.76078059, 0.54038843, 0.32175649, 0.32700502],
       [0.4038537 , 0.69838547, 0.91066267, 0.97244531],
       [0.20602581, 0.99823613, 0.0811806 , 0.19820333],
       [0.69663272, 0.6344365 , 0.92437254, 0.52098879]])

In [89]:
b

array([0.07084664, 0.21823642, 0.80769261, 0.08007351])

In [95]:
for i in range(4):
    b[i] = b[i]/A[i,i]
    A[i] = A[i]/A[i,i]

    for j in range(i+1,4):
        b[j] = b[j] - A[j,i]*b[i] 
        A[j] = A[j] - A[j,i]*A[i]
        

In [96]:
A

array([[ 1.        ,  0.71030786,  0.42292941,  0.42982829],
       [ 0.        ,  1.        ,  1.79785201,  1.94121267],
       [-0.        , -0.        ,  1.        ,  1.00424496],
       [-0.        , -0.        , -0.        ,  1.        ]])

In [97]:
b

array([ 1.29857191, -0.60412921, -0.7953961 , -0.65307564])

In [126]:
ls = [i for i in np.arange(2,-1,-1)]

In [127]:
ls

[2, 1, 0]